### ISSUE TITLE
No license on the base pom

### ISSUE THREAD

**Issue by hyandell** [HubSpot/basepom#108]
Noting that there is no license on this pom. I can see that you might not want to put a <license> tag in if children projects use differing licenses, but an xml comment on the pom would be useful.

Any thoughts on which license to consider this under?

(apologies for that all being a bit terse :) )

**Comment by jhaber** [comment]
Sorry about that, #109 adds an Apache 2.0 LICENSE file to the repo, would that do the trick?

**Comment by jhaber** [comment]
Whoops didn't mean to auto-close

**Comment by hyandell** [comment]
Thank you - adding that is great :)
